+ cd /Users/naquib/Github/depmap-portal/data-prep-pipeline/data_prep_pipeline/state/r40
+ EXIT_STATUS=0
+ '[' 0 == 0 ']'
+ trap 'kill -TERM $PID' TERM INT
+ PID=1716
+ wait 1716
+ python3 script_0
+ trap - TERM INT
+ wait 1716
+ EXIT_STATUS=0
+ '[' 0 == 0 ']'
+ trap 'kill -TERM $PID' TERM INT
+ PID=1754
+ wait 1754
+ python3 /Users/naquib/Github/depmap-portal/data-prep-pipeline/data_prep_pipeline/upload_to_taiga.py rnai_confounders.csv 'Update rnai_confounders data' predictability-76d5.132 RNAiConfounders csv_matrix
Traceback (most recent call last):
  File "/Users/naquib/Github/depmap-portal/data-prep-pipeline/data_prep_pipeline/upload_to_taiga.py", line 60, in <module>
    df = pd.read_csv(args.df_to_upload)
  File "/Users/naquib/Library/Caches/pypoetry/virtualenvs/data-prep-pipeline-C1Obh63D-py3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/Users/naquib/Library/Caches/pypoetry/virtualenvs/data-prep-pipeline-C1Obh63D-py3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/Users/naquib/Library/Caches/pypoetry/virtualenvs/data-prep-pipeline-C1Obh63D-py3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/naquib/Library/Caches/pypoetry/virtualenvs/data-prep-pipeline-C1Obh63D-py3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/naquib/Library/Caches/pypoetry/virtualenvs/data-prep-pipeline-C1Obh63D-py3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/naquib/Library/Caches/pypoetry/virtualenvs/data-prep-pipeline-C1Obh63D-py3.9/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/Users/naquib/Library/Caches/pypoetry/virtualenvs/data-prep-pipeline-C1Obh63D-py3.9/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'rnai_confounders.csv'
