__init__.py: error: Type "tuple[str, stat_result | None]" is not assignable to return type "Tuple[str, stat_result]"
common.py: error: Cannot access attribute "__fields__" for class "type[ResponseMixin]*"
conftest.py: error: Argument of type "Literal['read']" cannot be assigned to parameter "access_type" of type "AccessType" in function "__init__"
data_validation.py: error: Cannot access attribute "any" for class "ExtensionArray"
dataset.py: error: "value" is not a known attribute of "None" (reportOptionalMemberAccess)
dataset.py: error: Argument of type "type[DatasetFeature]" cannot be assigned to parameter "axis" of type "DatasetFeature | DatasetSample" in function "_get_indexes_by_given_id"
dataset.py: error: Argument of type "type[DatasetSample]" cannot be assigned to parameter "axis" of type "DatasetFeature | DatasetSample" in function "_get_indexes_by_given_id"
dataset_tasks.py: error: Type "None" is not assignable to declared type "List[Unknown]"
download_tasks.py: error: Argument of type "ArrayLike" cannot be assigned to parameter "column_labels" of type "List[str] | None" in function "_handle_df_nas"
download_tasks.py: error: Cannot access attribute "merge" for class "NDArray[Unknown]"
download_tasks.py: error: Cannot access attribute "merge" for class "ndarray[Any, Unknown]"
download_tasks.py: error: Cannot access attribute "merge" for class "ndarray[Any, _dtype]"
factories.py: error: "Meta" overrides symbol of same name in class "Factory"
factories.py: error: Argument of type "BytesIO | BinaryIO | None" cannot be assigned to parameter "file" of type "BytesIO" in function "create_upload_file"
factories.py: error: Argument of type "IdMapping | None" cannot be assigned to parameter "id_mapping" of type "Json[IdMappingInsanity] | None" in function "add_feature_type"
factories.py: error: Argument of type "Unknown | None" cannot be assigned to parameter "properties_to_index" of type "List[str]" in function "add_feature_type"
factories.py: error: Argument of type "Unknown | None" cannot be assigned to parameter "properties_to_index" of type "List[str]" in function "add_sample_type"
factories.py: error: Argument of type "_CallIfOmitted | Unknown" cannot be assigned to parameter "file" of type "BytesIO" in function "create_upload_file"
factories.py: error: Argument of type "_CallIfOmitted | Unknown" cannot be assigned to parameter "user" of type "str" in function "add_sample_type"
group.py: error: "group_entries" is not a known attribute of "None" (reportOptionalMemberAccess)
hdf5_utils.py: error: "Datatype" is not iterable
hdf5_utils.py: error: "__getitem__" method not defined on type "Datatype" (reportIndexIssue)
metadata.py: error: Cannot access attribute "value" for class "NDArray[Unknown]"
metadata.py: error: Cannot access attribute "value" for class "ndarray[Any, Unknown]"
proxy.py: error: Argument of type "bytes" cannot be assigned to parameter "data" of type "RequestData | None" in function "post"
test_compute.py: error: Argument missing for parameter "self" (reportCallIssue)
test_types.py: error: Cannot access attribute "id" for class "str"
